server:
  port: 8092
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zrowhsi/spring-cloud-config-store
          search-paths:
           - '*service'
          



